#!/usr/bin/env python3
"""SWIRL: bake TTF fonts into Dreamcast-ready bitmap fonts.

Output .swf layout (little endian):
  char magic[4] = "SWF2"; u16 tex_w, tex_h, size; i16 ascent, descent, line_h; u16 first, count;
  glyph[count] { u16 x, y; u8 w, h; i8 xoff, yoff; u8 adv, pad; }   (yoff relative to baseline)
  u8 alpha[tex_w * tex_h]  8 bit coverage, row order (square texture). SWIRL twiddles it at load and draws
                           it as an 8 bit paletted texture whose palette is white with 256 alpha levels.
Also writes ui/swirl/vmu_font.h (1-bit 5px pixel font for the VMU screen).
"""
import os, struct, sys
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
FONTS = os.path.join(ROOT, 'swirl', 'assets', 'fonts')
OUT = os.path.join(ROOT, 'ui', 'swirl', 'assets')
FIRST, LAST = 32, 126

SPECS = [  # name, file, variation, px size
    ('title', 'Sora.ttf', b'Bold', 30),
    ('head', 'Sora.ttf', b'Bold', 20),
    ('ui', 'Sora.ttf', b'SemiBold', 14),
    ('body', 'Barlow-Medium.ttf', None, 15),
    ('small', 'Barlow-SemiBold.ttf', None, 12),
]

def twiddle_index(x, y):
    r = 0
    for i in range(10):
        r |= ((y >> i) & 1) << (2 * i)
        r |= ((x >> i) & 1) << (2 * i + 1)
    return r

def bake(name, fname, var, size):
    font = ImageFont.truetype(os.path.join(FONTS, fname), size)
    if var:
        font.set_variation_by_name(var)
    ascent, descent = font.getmetrics()
    glyphs = []
    for c in range(FIRST, LAST + 1):
        ch = chr(c)
        l, t, r, b = font.getbbox(ch, anchor='ls')
        w, h = max(0, r - l), max(0, b - t)
        mask = Image.new('L', (w + 2, h + 2), 0)
        if w and h:
            ImageDraw.Draw(mask).text((1 - l, 1 - t), ch, font=font, fill=255, anchor='ls')
        glyphs.append((c, mask, l - 1, t - 1, int(round(font.getlength(ch)))))
    # shelf pack into smallest square
    for tex in (64, 128, 256, 512):
        x = y = shelf = 0
        pos = [None] * len(glyphs)
        ok = True
        order = sorted(range(len(glyphs)), key=lambda i: -glyphs[i][1].size[1])
        for i in order:
            c, m = glyphs[i][0], glyphs[i][1]
            gw, gh = m.size
            if x + gw > tex:
                x, y, shelf = 0, y + shelf, 0
            if y + gh > tex:
                ok = False
                break
            pos[i] = (x, y)
            x += gw
            shelf = max(shelf, gh)
        if ok:
            break
    atlas = Image.new('L', (tex, tex), 0)
    for (c, m, *_), (px, py) in zip(glyphs, pos):
        atlas.paste(m, (px, py))
    hdr = struct.pack('<4sHHHhhhHH', b'SWF2', tex, tex, size, ascent, -descent, ascent + descent, FIRST, len(glyphs))
    tbl = b''.join(struct.pack('<HHBBbbBB', px, py, m.size[0], m.size[1], xo, yo, adv, 0)
                   for (c, m, xo, yo, adv), (px, py) in zip(glyphs, pos))
    pix = atlas.tobytes()
    with open(os.path.join(OUT, f'font_{name}.swf'), 'wb') as f:
        f.write(hdr + tbl + pix)
    atlas.save(os.path.join(ROOT, 'swirl', 'build', f'font_{name}.png')) if os.path.isdir(os.path.join(ROOT, 'swirl', 'build')) else None
    print(f'{name}: {size}px atlas {tex}x{tex}')

def vmu_font():
    font = ImageFont.truetype(os.path.join(FONTS, 'Silkscreen.ttf'), 8)
    rows = []
    for c in range(FIRST, LAST + 1):
        ch = chr(c)
        im = Image.new('L', (12, 12), 0)
        ImageDraw.Draw(im).text((0, 0), ch, font=font, fill=255)
        adv = int(round(font.getlength(ch)))
        bits = []
        for y in range(4, 9):  # 5 rows cap height
            v = 0
            for x in range(8):
                if im.getpixel((x, y)) > 127:
                    v |= 0x80 >> x
            bits.append(v)
        rows.append((adv, bits))
    with open(os.path.join(ROOT, 'ui', 'swirl', 'vmu_font.h'), 'w') as f:
        f.write('/* Generated by swirl/tools/gen_fonts.py from Silkscreen (OFL). 5 rows, MSB = left pixel. */\n#pragma once\n#include <stdint.h>\n')
        f.write('static const uint8_t vmu_font_adv[95] = {%s};\n' % ','.join(str(a) for a, _ in rows))
        f.write('static const uint8_t vmu_font_rows[95][5] = {\n%s\n};\n' % ',\n'.join('  {%s}' % ','.join('0x%02X' % b for b in bits) for _, bits in rows))
    print('vmu font ok')

if __name__ == '__main__':
    os.makedirs(OUT, exist_ok=True)
    for s in SPECS:
        bake(*s)
    vmu_font()
